# Generated by Django 5.0.2 on 2024-03-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(help_text='Enter a valid Bank Name', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(help_text='Enter the county name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('financial_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_year', models.CharField(help_text='Enter a valid Financial Year', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(help_text='Enter a valid Institution Name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(help_text='Enter the constituency name', max_length=255, unique=True)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.county')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(help_text='Enter a valid Account Number', max_length=200, unique=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.bank')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id_no', models.CharField(help_text='Enter a valid National ID Number', max_length=200, unique=True)),
                ('registration_number', models.CharField(help_text='Enter a valid Student Registration Number', max_length=200, unique=True)),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=255)),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=255)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(help_text='Enter the ward name', max_length=200, unique=True)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id_no', models.CharField(help_text='Enter a valid National ID Number', max_length=200, unique=True)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.ward')),
            ],
        ),
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('bursary_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id_no', models.CharField(help_text='Enter a valid National ID Number', max_length=200)),
                ('registration_number', models.CharField(help_text='Enter a valid Student Registration Number', max_length=200)),
                ('account_number', models.CharField(help_text='Enter a valid Account Number', max_length=200)),
                ('serial_number', models.CharField(help_text='Auto-generated serial number', max_length=200, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, help_text='Amount disbursed in Ksh', max_digits=10, null=True)),
                ('date_disbursed', models.DateTimeField(blank=True, help_text='Date of disbursement', null=True)),
                ('financial_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.financialyear')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashinani.ward')),
            ],
        ),
    ]
