# Generated by Django 5.0.2 on 2024-02-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(help_text='Enter a valid Bank Name', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency', models.CharField(help_text='Enter the constituency', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('financial_year', models.CharField(help_text='Enter a valid Financial Year', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_name', models.CharField(help_text='Enter a valid Institution Name', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAccount',
            fields=[
                ('institution_account_number', models.CharField(blank=True, help_text='Enter a valid Institution Account Number', max_length=200, primary_key=True, serialize=False)),
                ('bank_name', models.ForeignKey(help_text='Enter a valid Bank Name', on_delete=django.db.models.deletion.CASCADE, to='mashinani.bank')),
                ('institution_name', models.ForeignKey(help_text='Enter a valid Institution Name', on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
            ],
        ),
        migrations.CreateModel(
            name='VoterRegister',
            fields=[
                ('national_id', models.CharField(help_text='Enter a valid National ID Number', max_length=200, primary_key=True, serialize=False)),
                ('constituency', models.ForeignKey(help_text='Enter the Constituency', on_delete=django.db.models.deletion.CASCADE, to='mashinani.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('registration_number', models.CharField(help_text='Enter a valid Student Registration Number', max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=255)),
                ('middle_name', models.CharField(help_text='Enter the middle name', max_length=255)),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=255)),
                ('institution_name', models.ForeignKey(help_text='Enter a Valid Institution', on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
                ('national_id', models.ForeignKey(help_text='Enter a valid National ID Number', on_delete=django.db.models.deletion.CASCADE, to='mashinani.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('serial_number', models.CharField(help_text='Auto-generated serial number', max_length=200, primary_key=True, serialize=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, help_text='Amount disbursed in Ksh', max_digits=10, null=True)),
                ('date_disbursed', models.DateTimeField(blank=True, help_text='Date of disbursement', null=True)),
                ('financial_year', models.ForeignKey(help_text='Enter a valid Financial Year', on_delete=django.db.models.deletion.CASCADE, to='mashinani.financialyear')),
                ('institution_name', models.ForeignKey(help_text='Enter a valid Institution Name', on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
                ('institution_account_number', models.ForeignKey(help_text='Enter a valid Institution Account Number', on_delete=django.db.models.deletion.CASCADE, to='mashinani.institutionaccount')),
                ('registration_number', models.ForeignKey(help_text='Enter a valid Student Registration Number', on_delete=django.db.models.deletion.CASCADE, to='mashinani.studentregister')),
                ('national_id', models.ForeignKey(help_text='Enter a valid National ID Number', on_delete=django.db.models.deletion.CASCADE, to='mashinani.voterregister')),
            ],
        ),
    ]
