# Generated by Django 5.0.2 on 2024-02-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('national_id', models.CharField(help_text='Enter a valid National ID Number', max_length=20, primary_key=True, serialize=False)),
                ('constituency', models.CharField(help_text='Enter the constituency', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(blank=True, help_text='Enter a valid National ID Number', max_length=20, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Enter a valid Student Registration Number', max_length=20, unique=True)),
                ('institution_account_number', models.CharField(blank=True, help_text='Enter a valid Institution Account Number', max_length=20)),
                ('financial_year', models.CharField(blank=True, help_text='Enter the financial year', max_length=10)),
                ('serial_number', models.CharField(blank=True, help_text='Auto-generated serial number', max_length=8, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, help_text='Amount disbursed in Ksh', max_digits=10, null=True)),
                ('date_disbursed', models.DateTimeField(blank=True, help_text='Date of disbursement', null=True)),
                ('institution', models.ForeignKey(help_text='Choose the Tertiary Institution', on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Enter a valid Student Registration Number', max_length=20, unique=True)),
                ('student_name', models.CharField(help_text="Enter the student's name", max_length=255)),
                ('institution', models.ForeignKey(help_text='Choose the Tertiary Institution', on_delete=django.db.models.deletion.CASCADE, to='mashinani.institution')),
            ],
        ),
    ]
