# Generated by Django 5.0.2 on 2024-03-04 15:23

from django.db import migrations

def insert_kenyan_banks(apps, schema_editor):
    Bank = apps.get_model('mashinani', 'Bank')
    banks_data = [
        {'bank_name': 'Equity Bank'},
        {'bank_name': 'KCB Bank'},
        {'bank_name': 'Co-operative Bank'},
        {'bank_name': 'Standard Chartered Bank'},
        {'bank_name': 'Barclays Bank'},
        {'bank_name': 'Absa Bank'},
        {'bank_name': 'National Bank of Kenya'},
        {'bank_name': 'DTB Bank'},
        {'bank_name': 'NCBA Bank'},
        {'bank_name': 'Family Bank'},
        {'bank_name': 'CBA Bank'},
        {'bank_name': 'Stanbic Bank'},
        {'bank_name': 'HF Group'},
        {'bank_name': 'Credit Bank'},
        {'bank_name': 'Gulf African Bank'},
        {'bank_name': 'I&M Bank'},
        {'bank_name': 'Bank of Africa'},
        {'bank_name': 'Chase Bank'},
        {'bank_name': 'Jamii Bora Bank'},
    ]
    
    for data in banks_data:
        Bank.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_kenyan_banks),
    ]
