# Generated by Django 5.0.2 on 2024-02-18 19:38

from django.db import migrations

def add_kenyan_banks(apps, schema_editor):
    Bank = apps.get_model('mashinani', 'Bank')
    
    kenyan_banks = [
        "Kenya Commercial Bank",
        "Equity Bank",
        "Cooperative Bank",
        "Standard Chartered Bank",
        "Barclays Bank",
        "Absa Bank",
        "National Bank of Kenya",
        "Diamond Trust Bank",
        "KCB Group",
        "NIC Bank",
        "Chase Bank",
        "Family Bank",
        "Imperial Bank",
        "Consolidated Bank of Kenya",
        "Jamii Bora Bank",
        "I&M Bank",
        "Ecobank Kenya",
        "Credit Bank",
        "Victoria Commercial Bank",
        "Gulf African Bank",
        "Prime Bank",
        "Bank of Africa",
        "Spire Bank",
        "Housing Finance",
        "Guardian Bank",
        "First Community Bank",
        "Paramount Universal Bank",
        "Faulu Kenya",
        "Equatorial Commercial Bank",
        "TransNational Bank",
        # Add more Kenyan banks as needed
    ]

    for bank_name in kenyan_banks:
        Bank.objects.get_or_create(bank_name=bank_name)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0002_auto_20240218_2236'),
    ]

    operations = [
        migrations.RunPython(add_kenyan_banks),
    ]
