# Generated by Django 5.0.2 on 2024-03-05 06:52

from django.db import migrations

def insert_kenyan_institutions(apps, schema_editor):
    Institution = apps.get_model('mashinani', 'Institution')
    institutions_data = [
        {'institution_name': 'University of Nairobi'},
        {'institution_name': 'Kenyatta University'},
        {'institution_name': 'Strathmore University'},
        {'institution_name': 'Egerton University'},
        {'institution_name': 'Moi University'},
        {'institution_name': 'Jomo Kenyatta University of Agriculture and Technology'},
        {'institution_name': 'Daystar University'},
        {'institution_name': 'United States International University-Africa'},
        {'institution_name': 'Maseno University'},
        {'institution_name': 'Technical University of Kenya'},
        {'institution_name': 'Masinde Muliro University of Science and Technology'},
        # Add more universities and colleges as needed
    ]
    
    for data in institutions_data:
        Institution.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0002_auto_20240305_0952'),
    ]

    operations = [
        migrations.RunPython(insert_kenyan_institutions),
    ]
