# Generated by Django 5.0.2 on 2024-02-18 19:43
from django.db import migrations
import random

def generate_unique_account_number(existing_account_numbers):
    while True:
        account_number = str(random.randint(100_000_000, 999_999_999))
        if account_number not in existing_account_numbers:
            return account_number

def insert_institution_accounts(apps, schema_editor):
    InstitutionAccount = apps.get_model('mashinani', 'InstitutionAccount')
    Institution = apps.get_model('mashinani', 'Institution')
    Bank = apps.get_model('mashinani', 'Bank')

    universities_list = [
        "University of Nairobi",
        "Kenyatta University",
        "Egerton University",
        "Moi University",
        "Strathmore University",
        "Jomo Kenyatta University of Agriculture and Technology",
        "Maseno University",
        "Kisii University",
        "Technical University of Kenya",
        "United States International University",
        "Daystar University",
        "Mount Kenya University",
        "African Virtual University",
        "Maasai Mara University",
        "Pwani University",
        "University of Eastern Africa, Baraton",
        "Kiriri Women's University of Science and Technology",
        "KCA University",
        "Zetech University",
        "Multimedia University of Kenya",
        "Scott Christian University",
        "Great Lakes University of Kisumu",
        "Kenya Highlands Evangelical University",
        "Presbyterian University of East Africa",
        "African Nazarene University",
        "Adventist University of Africa",
        "St. Paul's University",
        "Riara University",
        "Pan Africa Christian University",
        "Management University of Africa",
        "International Leadership University",
        "Africa International University",
        "Kirinyaga University",
        "Karatina University",
        # Add more university names as needed
    ]

    colleges_list = [
        "Kenya Medical Training College",
        "Technical University of Mombasa",
        "Eldoret Polytechnic",
        "Kenya Institute of Management",
        "Kabete National Polytechnic",
        "Kisumu National Polytechnic",
        "Rift Valley Institute of Science and Technology",
        "Meru National Polytechnic",
        "Kenya Institute of Mass Communication",
        "Kiambu Institute of Science and Technology",
        "Machakos Institute of Technology",
        "Thika Technical Training Institute",
        "Kisii National Polytechnic",
        "Mombasa Technical Training Institute",
        "Kakamega National Polytechnic",
        "Nairobi Technical Training Institute",
        "Karen Technical Training Institute",
        "Kaimosi Friends University College",
        "Kenya Water Institute",
        "Kenya Utalii College",
        "Kenya Institute of Highways and Building Technology",
        "Co-operative University of Kenya",
        "Murang'a University College",
        "Kisumu Polytechnic",
        "Nairobi Institute of Business Studies",
        "Eldoret Technical Training Institute",
        "East Africa School of Aviation",
        "Railway Training Institute",
        "Kenya Forestry College",
        "Kenya Institute of Surveying and Mapping",
        "Machakos University",
        "St. Joseph's Technical Institute",
        "Kenya Utalii College",
        "Mwangaza College",
        "Kenya School of Government",
        "Eldoret Aviation Training Institute",
        "Baraton Teachers' Training College",
        "Kisii College of Accountancy",
        "Kenya Utalii College",
        "Mathenge Technical Training Institute",
        "Nairobi Aviation College",
        "Rift Valley Technical Training Institute",
        "The Kenya Polytechnic University College",
        "Kenya Institute of Supplies Management",
        "Kitale Technical Training Institute",
        # Add more college names as needed
    ]

    kenyan_banks = [
        "Kenya Commercial Bank",
        "Equity Bank",
        "Cooperative Bank",
        "Standard Chartered Bank",
        "Barclays Bank",
        "Absa Bank",
        "National Bank of Kenya",
        "Diamond Trust Bank",
        "KCB Group",
        "NIC Bank",
        "Chase Bank",
        "Family Bank",
        "Imperial Bank",
        "Consolidated Bank of Kenya",
        "Jamii Bora Bank",
        "I&M Bank",
        "Ecobank Kenya",
        "Credit Bank",
        "Victoria Commercial Bank",
        "Gulf African Bank",
        "Prime Bank",
        "Bank of Africa",
        "Spire Bank",
        "Housing Finance",
        "Guardian Bank",
        "First Community Bank",
        "Paramount Universal Bank",
        "Faulu Kenya",
        "Equatorial Commercial Bank",
        "TransNational Bank",
        # Add more Kenyan banks as needed
    ]

    # Get existing account numbers
    existing_account_numbers = set(InstitutionAccount.objects.values_list('institution_account_number', flat=True))

    # Create InstitutionAccount instances for Universities
    for university_name in universities_list:
        institution = Institution.objects.get(institution_name=university_name)
        bank = Bank.objects.get(bank_name="Kenya Commercial Bank")  # Choose a default bank for universities
        account_number = generate_unique_account_number(existing_account_numbers)
        existing_account_numbers.add(account_number)
        InstitutionAccount.objects.get_or_create(
            institution_account_number=account_number,
            institution_name=institution,
            bank_name=bank
        )

    # Create InstitutionAccount instances for Colleges
    for college_name in colleges_list:
        institution = Institution.objects.get(institution_name=college_name)
        bank = Bank.objects.get(bank_name="Kenya Commercial Bank")  # Choose a default bank for colleges
        account_number = generate_unique_account_number(existing_account_numbers)
        existing_account_numbers.add(account_number)
        InstitutionAccount.objects.get_or_create(
            institution_account_number=account_number,
            institution_name=institution,
            bank_name=bank
        )

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0003_auto_20240218_2238'),  # Update with the latest migration name
    ]

    operations = [
        migrations.RunPython(insert_institution_accounts),
    ]