# Generated by Django 5.0.2 on 2024-03-05 06:52

from django.db import migrations

def insert_account_data(apps, schema_editor):
    Account = apps.get_model('mashinani', 'Account')
    Institution = apps.get_model('mashinani', 'Institution')
    Bank = apps.get_model('mashinani', 'Bank')

    # Fetching existing institutions and banks data
    university_of_nairobi = Institution.objects.get(institution_name='University of Nairobi')
    kenyatta_university = Institution.objects.get(institution_name='Kenyatta University')
    strathmore_university = Institution.objects.get(institution_name='Strathmore University')
    egerton_university = Institution.objects.get(institution_name='Egerton University')
    moi_university = Institution.objects.get(institution_name='Moi University')
    jkuat = Institution.objects.get(institution_name='Jomo Kenyatta University of Agriculture and Technology')
    daystar_university = Institution.objects.get(institution_name='Daystar University')
    usiu_africa = Institution.objects.get(institution_name='United States International University-Africa')
    maseno_university = Institution.objects.get(institution_name='Maseno University')
    tuk = Institution.objects.get(institution_name='Technical University of Kenya')
    mmust = Institution.objects.get(institution_name='Masinde Muliro University of Science and Technology')

    equity_bank = Bank.objects.get(bank_name='Equity Bank')
    kcb_bank = Bank.objects.get(bank_name='KCB Bank')
    cooperative_bank = Bank.objects.get(bank_name='Co-operative Bank')
    standard_chartered_bank = Bank.objects.get(bank_name='Standard Chartered Bank')
    barclays_bank = Bank.objects.get(bank_name='Barclays Bank')
    absa_bank = Bank.objects.get(bank_name='Absa Bank')
    national_bank = Bank.objects.get(bank_name='National Bank of Kenya')
    dtb_bank = Bank.objects.get(bank_name='DTB Bank')
    ncba_bank = Bank.objects.get(bank_name='NCBA Bank')
    family_bank = Bank.objects.get(bank_name='Family Bank')
    cba_bank = Bank.objects.get(bank_name='CBA Bank')
    stanbic_bank = Bank.objects.get(bank_name='Stanbic Bank')
    hf_group = Bank.objects.get(bank_name='HF Group')
    credit_bank = Bank.objects.get(bank_name='Credit Bank')
    gulf_african_bank = Bank.objects.get(bank_name='Gulf African Bank')
    im_bank = Bank.objects.get(bank_name='I&M Bank')
    bank_of_africa = Bank.objects.get(bank_name='Bank of Africa')
    chase_bank = Bank.objects.get(bank_name='Chase Bank')
    jamii_bora_bank = Bank.objects.get(bank_name='Jamii Bora Bank')

    accounts_data = [
        {'institution_id': university_of_nairobi, 'bank_id': equity_bank, 'account_number': '1234567890'},
        {'institution_id': kenyatta_university, 'bank_id': kcb_bank, 'account_number': '2345678901'},
        {'institution_id': strathmore_university, 'bank_id': cooperative_bank, 'account_number': '3456789012'},
        {'institution_id': egerton_university, 'bank_id': standard_chartered_bank, 'account_number': '4567890123'},
        {'institution_id': moi_university, 'bank_id': barclays_bank, 'account_number': '5678901234'},
        {'institution_id': jkuat, 'bank_id': absa_bank, 'account_number': '6789012345'},
        {'institution_id': daystar_university, 'bank_id': national_bank, 'account_number': '7890123456'},
        {'institution_id': usiu_africa, 'bank_id': dtb_bank, 'account_number': '8901234567'},
        {'institution_id': maseno_university, 'bank_id': ncba_bank, 'account_number': '9012345678'},
        {'institution_id': tuk, 'bank_id': family_bank, 'account_number': '0123456789'},
        {'institution_id': mmust, 'bank_id': cba_bank, 'account_number': '0987654321'},
        # Add more accounts as needed
    ]

    for data in accounts_data:
        Account.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0003_auto_20240305_0952'),
    ]

    operations = [
        migrations.RunPython(insert_account_data),
    ]
