# Generated by Django 5.0.2 on 2024-03-04 15:29

from django.db import migrations

def insert_counties(apps, schema_editor):
    County = apps.get_model('mashinani', 'County')
    counties_data = [
        {'county_name': 'Kisumu'},
        {'county_name': 'Siaya'},
        {'county_name': 'Homabay'},
        {'county_name': 'Migori'},
        {'county_name': 'Kisii'},
        {'county_name': 'Nyamira'},
    ]

    for data in counties_data:
        County.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0004_auto_20240304_1827'),
    ]

    operations = [
        migrations.RunPython(insert_counties),
    ]
