# Generated by Django 5.0.2 on 2024-02-26 15:30
from django.db import migrations

def insert_constituencies(apps, schema_editor):
    Constituency = apps.get_model('mashinani', 'Constituency')
    constituencies_data = [
        {'constituency_name': 'Kisumu West'},
        {'constituency_name': 'Kisumu East'},
        {'constituency_name': 'Kisumu Central'},
        {'constituency_name': 'Seme'},
        {'constituency_name': 'Nyando'},
        {'constituency_name': 'Muhoroni'},
        {'constituency_name': 'Nyakach'},
    ]

    for data in constituencies_data:
        Constituency.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0004_auto_20240226_1813'),
    ]

    operations = [
        migrations.RunPython(insert_constituencies),
    ]
