# Generated by Django 5.0.2 on 2024-02-26 15:24
from django.db import migrations

def insert_voters(apps, schema_editor):
    Voter = apps.get_model('mashinani', 'Voter')
    Constituency = apps.get_model('mashinani', 'Constituency')

    # Fetching existing constituencies data
    kisumu_west = Constituency.objects.get(constituency_name='Kisumu West')

    voters_data = []
    for i in range(50):
        voters_data.append({'constituency_id': kisumu_west, 'national_id_no': '1{:07}'.format(i)})

    for data in voters_data:
        Voter.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0005_auto_20240226_1821'),
    ]

    operations = [
        migrations.RunPython(insert_voters),
    ]
