# Generated by Django 5.0.2 on 2024-03-05 06:52

from django.db import migrations

def insert_constituency_data(apps, schema_editor):
    Constituency = apps.get_model('mashinani', 'Constituency')
    County = apps.get_model('mashinani', 'County')

    # Fetching existing counties
    kisumu = County.objects.get(county_name='Kisumu')
    
    constituency_data = [
        {'county_id': kisumu, 'constituency_name': 'Kisumu West'},
        {'county_id': kisumu, 'constituency_name': 'Kisumu East'},
        {'county_id': kisumu, 'constituency_name': 'Kisumu Central'},
        {'county_id': kisumu, 'constituency_name': 'Nyando'},
        {'county_id': kisumu, 'constituency_name': 'Nyakatch'},
        {'county_id': kisumu, 'constituency_name': 'Seme'},
        # Add more constituencies as needed
    ]

    for data in constituency_data:
        Constituency.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0005_auto_20240305_0952'),
    ]

    operations = [
        migrations.RunPython(insert_constituency_data),
    ]
