# Generated by Django 5.0.2 on 2024-03-05 06:52

from django.db import migrations

def insert_ward_data(apps, schema_editor):
    Ward = apps.get_model('mashinani', 'Ward')
    Constituency = apps.get_model('mashinani', 'Constituency')

    # Fetching existing constituencies
    kisumu_west = Constituency.objects.get(constituency_name='Kisumu West')
    
    ward_data = [
        {'constituency_id': kisumu_west, 'ward_name': 'North Kisumu'},
        {'constituency_id':kisumu_west , 'ward_name': 'North West Kisumu'},
        {'constituency_id':kisumu_west , 'ward_name': 'West Kisumu'},
        {'constituency_id':kisumu_west , 'ward_name': 'South West Kisumu'},
        {'constituency_id':kisumu_west , 'ward_name': 'Central Kisumu'},

        # Add more wards as needed
    ]

    for data in ward_data:
        Ward.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0006_auto_20240305_0952'),
    ]

    operations = [
        migrations.RunPython(insert_ward_data),
    ]
