# Generated by Django 5.0.2 on 2024-03-04 17:45

from django.db import migrations

def insert_students(apps, schema_editor):
    import random

    Student = apps.get_model('mashinani', 'Student')
    Institution = apps.get_model('mashinani', 'Institution')

    # Fetching existing institutions data
    institutions = Institution.objects.all()

    first_names = ['John', 'Jane', 'Mary', 'Peter', 'Alice', 'David', 'Grace', 'Kevin', 'Mercy', 'Brian']
    last_names = ['Omondi', 'Wanjiru', 'Kiptoo', 'Njoroge', 'Mwangi', 'Kamau', 'Musyoka', 'Korir', 'Atieno', 'Ochieng']

    students_data = []

    for i in range(50):
        student_data = {
            'national_id_no': '1{:07}'.format(i),
            'institution_id': random.choice(institutions),
            'registration_number': 'STU{:03}'.format(i + 1),
            'first_name': random.choice(first_names),
            'last_name': random.choice(last_names),
        }
        students_data.append(student_data)

    for data in students_data:
        Student.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0007_auto_20240304_1847'),
    ]

    operations = [
        migrations.RunPython(insert_students),
    ]
