# Generated by Django 5.0.2 on 2024-03-04 17:45

from django.db import migrations

def insert_residents(apps, schema_editor):
    import random

    Resident = apps.get_model('mashinani', 'Resident')
    Ward = apps.get_model('mashinani', 'Ward')

    # Fetching existing wards data
    wards = Ward.objects.all()

    residents_data = []

    for i in range(50):
        resident_data = {
            'national_id_no': '1{:07}'.format(i),
            'ward_id': random.choice(wards),
        }
        residents_data.append(resident_data)

    for data in residents_data:
        Resident.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0007_auto_20240304_1847'),
    ]

    operations = [
        migrations.RunPython(insert_residents),
    ]
