# Generated by Django 5.0.2 on 2024-03-05 06:52

from django.db import migrations

def insert_financial_year(apps, schema_editor):
    FinancialYear = apps.get_model('mashinani', 'FinancialYear')

    financial_year_data = [
        {'financial_year': '2023/2024'},
        {'financial_year': '2024/2025'},
        {'financial_year': '2025/2026'},
        {'financial_year': '2026/2027'},
        # Add more financial years as needed
    ]

    for data in financial_year_data:
        FinancialYear.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0008_auto_20240305_0952'),
    ]

    operations = [
        migrations.RunPython(insert_financial_year),
    ]
